#spring.application.name=BootMVCProj07-MiniProject-CURDOperations

#view resolver
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

#embedded serverPortNumber
server.port=4041

#Context path
server.servlet.context-path=/Mini-Proj07

#DataSource Configuration
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
spring.datasource.username=manoj
spring.datasource.password=manoj2723

#Hibernate-jpa properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect





#serverManaged DataSource

#spring.datasource.jndi-name=java:comp/env/jdbc/myDataSource
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver










































