spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
spring.datasource.username=manoj
spring.datasource.password=manoj2723
server.port=4041
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
file.upload-dir=uploads